### ISSUE TITLE
Performance of plots is terrible sometimes

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#1001]
Test code:

```
# import observed data (will return a list of DataSet objects)
dataSet <- loadDataSetsFromExcel(
  xlsFilePath = getTestDataFilePath("CompiledDataSetStevens2012.xlsx"),
  importerConfiguration = loadDataImporterConfiguration(getTestDataFilePath("ImporterConfiguration.xml"))
)
# observed only
myCombDat <- DataCombined$new()
myCombDat$addDataSets(dataSet)

plotConfiguration <- ospsuite::DefaultPlotConfiguration$new()
plotConfiguration$xUnit <- ospUnits$Time$`week(s)`
plotConfiguration$legendTitleSize <- 8
```

and then creating the plot:

`plotIndividualTimeProfile(myCombDat, plotConfiguration)`

it takes sometimes insanely long until the figure is displayed, sometimes ony parts are displayed (e.g. only axis, or only error bars without points and axis, etc) first. Warnings show things like 

```
In rootVP(pvp) : reached elapsed time limit

In drawGTree(x) : reached elapsed time limit
Warning message:
In gp$fill : reached elapsed time limit
```

Something must be very inefficient, feels like some loops or whatever. This must be improved.

**Comment by IndrajeetPatil** [comment]
> it takes sometimes insanely long until the figure is displayed, sometimes ony parts are displayed (e.g. only axis, or only error bars without points and axis, etc) first.

For issues like this, we need a reproducible example. Otherwise, it's difficult to say where these problems are coming from. Often times, `reached elapsed time limit` issue solves itself if you force garbage collection with `gc()`, but it can also represent something more systematic. Hard to say without a reproducible example. 

Profiling `plotIndividualTimeProfile(myCombDat, plotConfiguration)` shows what's taking so long:

![image](https://user-images.githubusercontent.com/11330453/173579711-49b87037-39f8-424a-92c6-cd84d5321215.png)

Need to see which of these can be sped up.

**Comment by msevestre** [comment]
Time looks good to me on your profiling;-)

**Comment by PavelBal** [comment]
Best to show it in a video call.

**Comment by IndrajeetPatil** [comment]
I think this can be closed?

Using AGG graphics device seems to help with this issue.

**Comment by PavelBal** [comment]
Yes
