### ISSUE TITLE
Improve navigation of the documentation

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#1007]
1) Add an overview of all vignettes (now they can obly be found when clicking on "articles", which is not intuitive):
![image](https://user-images.githubusercontent.com/25903040/175545797-72247496-9d6c-4364-b52b-fb65ba65f87d.png)

2) THe link to the "online documentation" leads to the same page :)

![image](https://user-images.githubusercontent.com/25903040/175545890-7f6f6f3d-ec09-4da6-ad74-14b56150f7f8.png)

**Comment by IndrajeetPatil** [comment]
1. We do include such an overview in "Get Started" [article](https://www.open-systems-pharmacology.org/OSPSuite-R/articles/ospsuite.html). Is that not enough? What'd be a good place to include such an overview? Homepage?

![image](https://user-images.githubusercontent.com/11330453/177183858-3e7a3df3-fca6-4e7d-b009-a6b08de312e1.png)

2. The homepage for the package website is generated using `README.md`, which is where this sentence is included because we would like the users to check out the website if they are reading the GitHub README. I am not sure how we can avoid this. Maybe we can just remove this sentence from README. It's not too difficult to find the website:

![image](https://user-images.githubusercontent.com/11330453/177184359-809a18f9-10d4-44bc-b0eb-70863827ac8f.png)

**Comment by msevestre** [comment]
Bump what?😁

**Comment by IndrajeetPatil** [comment]
I am awaiting a response to my comment from Pavel, so the bump was just a reminder :)
