### ISSUE TITLE
LLOQ as a vector

### ISSUE THREAD

**Issue by pchelle** [Open-Systems-Pharmacology/OSPSuite-R#1124]
Is it possible to implement LLOQ as a vector of same size as `xValues` and `yValues` ?
Currently, it can only be of length 1

**Comment by PavelBal** [comment]
Do you mean the `DataSet` class? In that case, I don't think this is a good idea. 

- It would be a breaking change, not good
- `DataSet` is a wrapper around `DataRepository`, where LLOQ is a single value. A vector implies that the values can be different, which they are not. What should happen, if the user tries to provide a vector with different values?

Futhermore - `dataSetToDataFrame()` returns a data frame where LLOQ is a vector... Can't you just use it?

**Comment by pchelle** [comment]
> Do you mean the `DataSet` class? In that case, I don't think this is a good idea.

Yes, it is indeed for `DataSet` class.

>     A vector implies that the values can be different, which they are not. 

I thought the values could be different and lloq was a function of which reagents, calibrations and dilutions are used by the assay (eg. measuring high vs low concentrations may require different dilutions and would have different lloq) unless you assume they would be included as a different `DataSet` .
I actually don't know what should be the expected behaviour for this and hoped for the more flexible case

> What should happen, if the user tries to provide a vector with different values?

```r
> dataSet <- DataSet$new(name = "a")
> dataSet$LLOQ <- c(1,2)
Error in clrCallStatic(clrFacadeTypeName, "SetFieldOrProperty", objOrType,  : 
  Type:    System.ArgumentException
Message: Object of type 'System.Double[]' cannot be converted to type 'System.Nullable`1[System.Double]'.
Method:  System.Object TryChangeType(System.Object, System.Reflection.Binder, System.Globalization.CultureInfo, Boolean)
Stack trace:
   at System.RuntimeType.TryChangeType(Object value, Binder binder, CultureInfo culture, Boolean needsSpecialCast)
   at System.Reflection.MethodBase.CheckArguments(Object[] parameters, Binder binder, BindingFlags invokeAttr, CultureInfo culture, Signature sig)
   at System.Reflection.RuntimeMethodInfo.InvokeArgumentsCheck(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at Rclr.ClrFacade.SetFieldOrProperty(Object obj, String n
```

> Futhermore - `dataSetToDataFrame()` returns a data frame where LLOQ is a vector... Can't you just use it?

Not in the Reporting Engine case where you start directly with a user-defined dataset with LLOQ defined as a column (hence a vector with potentially different values). The goal was to refactor RE functions using `DataSet` objects instead.

**Comment by PavelBal** [comment]
We explicitly specified during the development of Data importer of PK-Sim that one data set can only have one LLOQ. That implies that all data sets coming from PK-Sim will have only one LLOQ value, therefore I am a bit surprized that ReportingEngine uses data sets with different LLOQs...

At any rate, I just realized that the `DataSet` class simply cannot have a vector with different LLOQ values because the underlying .NET class does not support it.

**Comment by Yuri05** [comment]
>We explicitly specified during the development of Data importer of PK-Sim that one data set can only have one LLOQ.

Reporting Engine does not nessesarily use observed data previously imported in PK-Sim.
It can also use completely independent data files (e.g. nonmem datasets) where LLOQ is provided as a column and thus can be (potentially) different within a dataset.

@pchelle As it is not possible to set different lloqs per dataset at the moment, RE should compare all lloqs of the dataset which are not null. If they are all the same (within reliable tolerance) - take it as the (only) lloq value. Otherwise: error

>
```
> dataSet$LLOQ <- c(1,2)
Error in clrCallStatic(clrFacadeTypeName, "SetFieldOrProperty", objOrType,  : 
  Type:    System.ArgumentException
Message: Object of type 'System.Double[]' cannot be converted to type 'System.Nullable`1[System.Double]'.
```

@PavelBal Any chance to get more explicite error message here?

**Comment by PavelBal** [comment]
> @PavelBal Any chance to get more explicite error message here?

Coming in next PR.

**Comment by PavelBal** [comment]
```
>   dataSet <- DataSet$new(name = dataSetName)
> dataSet$LLOQ <- c(0.25, 0.25)
Error in (function (value)  : 
  Only one LLOQ value per `DataSet` is supported! Please provide a scalar value and not a vector.
```
