### ISSUE TITLE
Path as vector of strings or as a string separated by "|"?

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#123]
From https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/110
I thinkg this is a separate issue. And I think Michael is right, using the "full" path with entries separated by "|" is more consistent with the whole OSPS. This way the user can even cope the path from MoBi and it will be valid. And also the csv-sheets that can be read by MoBi for parameter values always rely on "|" paths.

So maybe we should change how we create paths. Question is - should this be done in R (i.e., splitting the provided path to an array of strings, and passing it to .NET as we do now) or in .NET?

**Comment by msevestre** [comment]
@PavelBal I'd suggest to path the string directly to .NET because this is the first thing I need to do in the core implementation: Creating a path from the array. That way, we do not have to do that at all. 

I can implement this now if you agree. Then I'll update the code to match. After that, you can update the code to support multiple path. Agree?

**Comment by PavelBal** [comment]
OK, great.

**Comment by msevestre** [comment]
Going to implement of your branch for now.
