### ISSUE TITLE
PKSim minimal version outdated?

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#1321]
The `Core` in PKSim minimal is 12.0.76.0, while the package uses 12.0.223.0 (and PK-Sim nightly has an even newer version!)

**Comment by PavelBal** [comment]
@Felixmil @rwmcintosh  could you check this out please? Why is the created minimal version not the latest?

**Comment by rwmcintosh** [comment]
Hah, very good timing here. 
The reason the portable is outdated is that PK-Sim nightly has had failing integration tests.

There is a PR I just created for that and a few other things:
https://github.com/Open-Systems-Pharmacology/PK-Sim/pull/2821

I'll update the OSPSuite.Core version now and if the above PR is merged by the time the nightly goes, it will be fixed. Otherwise we can request a fresh nightly after it is merged.
