### ISSUE TITLE
Access functions directly, without refering to the package

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#134]
I.e., `rClr::clrCall()`  will be `clrCall()`

**Comment by PavelBal** [comment]
>  :: adds approximately 5 µs to function evaluation time

http://r-pkgs.had.co.nz/namespace.html

Not critical, but for rclr and R6 it's obvious where the functions come from.

**Comment by msevestre** [comment]
I disagree with this changes. Removing the namespace makes the code ambiguous. With the namespace , I do not have to think twice about where the method is coming from. 
Also it is advised in package development to reference other packages using the namespace (I have to find the links again but I have read it many time).

**Comment by msevestre** [comment]
Actually the same link provided above also suggests to use the namespace version for calling methods.
Because we hardly ever call those methods, at least for rclr I would definitely keep it

For R6, I can see here the exception because we treat the package somewhat as a core package (and I will not be surprised if it moves to r base in the future). That would be the only exception to the rule that I would consider.

**Comment by PavelBal** [comment]
OK, will revert the changes.

Thouth I don't  think that calling rclr is ambiguous as all the methods from the package start with `rclr`.

**Comment by msevestre** [comment]
It's clear for now. But what if we call a method clrConverter or whatever. How do we know where it comes dromt.
Plus it's a matter of convention. If you do it, you don't have to think about it
