### ISSUE TITLE
Version incrementation in main-workflow.yaml

### ISSUE THREAD

**Issue by Yuri05** [Open-Systems-Pharmacology/OSPSuite-R#1476]
In the [last workflow run](https://github.com/Open-Systems-Pharmacology/OSPSuite-R/actions/runs/10141825445) the version was properly incremented from `12.1.0.9000` to `12.1.0.9001` and commited:
https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/1a5e1931bb030ced71aee0a5dede936413789b86/DESCRIPTION#L4

However the created artifact still has the version `12.1.0.9000` (and indeed contains the package version `12.1.0.9000`).

In the workflow the incrementation of the version is the very first step, so not sure why this happens.

**Comment by Felixmil** [comment]
It looks like the R CMD actions checkout the merge commit instead of the last one (the version bump):

Here is the commit that is fetched:
![image](https://github.com/user-attachments/assets/8d15463b-2bf9-42b7-a6e1-8efa613fc2ff)

Here is the last commit list
![image](https://github.com/user-attachments/assets/db982f3b-5871-4435-8fea-125545cf9c43)

I will look into the checkout action parameters to make sure to get the last commit.

**Comment by Felixmil** [comment]
It looks like [this](https://github.com/actions/checkout?tab=readme-ov-file#checkout-pull-request-head-commit-instead-of-merge-commit) could be the solution.

I'll do some tests
