### ISSUE TITLE
$print of OutputSelections does not show the observer type

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#158]
```
OutputSelections : 
  Organism|PeripheralVenousBlood|Caffeine|Plasma (Peripheral Venous Blood): 
  Organism|ArterialBlood|Plasma|Caffeine|Concentration in container: 
  Organism|ArterialBlood|Plasma|Caffeine|Plasma Unbound: 
  Organism|ArterialBlood|BloodCells|Caffeine|Concentration in container: 
  Organism|ArterialBlood|Caffeine|Whole Blood: 
  Organism|LargeIntestine|Plasma|Caffeine: Drug
  Organism|Kidney|Plasma|Caffeine: Drug
  Organism|SmallIntestine|Plasma|Caffeine: Drug
  Organism|Brain|Plasma|Caffeine: Drug
  Organism|Skin|Plasma|Caffeine: Drug
  Organism|ArterialBlood|Plasma|Caffeine: Drug
  Organism|Bone|Plasma|Caffeine: Drug
  Organism|PortalVein|Plasma|Caffeine: Drug
  Organism|VenousBlood|Plasma|Caffeine: Drug
  Organism|Lung|Plasma|Caffeine: Drug
  Organism|Stomach|Plasma|Caffeine: Drug
  Organism|Fat|Plasma|Caffeine: Drug
  Organism|Spleen|Plasma|Caffeine: Drug
  Organism|Pancreas|Plasma|Caffeine: Drug
  Organism|Heart|Plasma|Caffeine: Drug
  Organism|Gonads|Plasma|Caffeine: Drug
  Organism|Muscle|Plasma|Caffeine: Drug
  Organism|Liver|Volume: Parameter
```

Empty space after `:` for the observer outputs. @msevestre I suppose it is a wrong definition in the enum `QuantityType`?

**Comment by msevestre** [comment]
> I suppose it is a wrong definition in the enum QuantityType?

No. Observertype are combined types and that's why it does not work (for example Observer | Drug)
We might have to rely on a .NET implementation for that instead or maybe you have a way to do it in R 

That's why the QuantityType are defined using binary numbers so that you can conbine them. We need to retrieve each bite separately basically

**Comment by PavelBal** [comment]
Ok, so what would be the solution here? :D I don't fully undestand.

**Comment by msevestre** [comment]
We have to mess around with bit opeartor.
Some quantities are a combination of type (e.g. Drug|observer)
Our enum only has Drug or Observer but the value returned is Drug + Observer. So we need to be able to find all enum values fullfiling the predicament

Maybe we could retrieve this from .NEt directly instead of computing it in R (slow). Unless there is aw  way to to bitwise operation in R (probably)
