### ISSUE TITLE
Update output format to match TLF requirement

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#193]
FYI: @PavelBal 
The values array is the concatenation of all the individual values!

I have 129 points. 10 indiviudal, my x array has 129 entries. My y array has 1290 entries!

```
outputValues <- getOutputValues(populationResults, populationResults$allQuantityPaths )
t <- outputValues[[1]]
 length(t$x)
[1] 129
> length(t$y)
[1] 1290
```

**Comment by msevestre** [comment]
ok it's because y is a matrix of 129 rows and 10 columns.

**Comment by msevestre** [comment]
@PavelBal Which makes me wonder if this structure is  the right default structure for a population?
 
@Yuri05 Based on the TLF Library, how should we organize our outputs

**Comment by msevestre** [comment]
@abdullahhamadeh What should be according to you the best structure for the output so that we can consume the TLF function almost out of the box to graph standard plots such as mean and percentile of a population simulation?

**Comment by abdullahhamadeh** [comment]
Typically (and perhaps most naturally) you might have this:
![image](https://user-images.githubusercontent.com/18409098/66339078-5d905780-e910-11e9-96b6-4136a49a3bfe.png)

But this isn't the best format for ggplot.  A better format is 

![image](https://user-images.githubusercontent.com/18409098/66339095-64b76580-e910-11e9-9120-dc8b3f663bca.png)

aka tidy format.  Of course instead of experiment number you might have IndividualID.

I believe the reshape2 toolbox can transform the first format to the second, so it's ok if we have the first format, but the user will have the extra step of needing to specify which columns belong to which experiment.

**Comment by msevestre** [comment]
@abdullahhamadeh mean and std etc... will be calculated using some of the function you wrote
What comes out of the population engine is per simulated path, a matric of values (one for each indiviudal). Alternatively, it could be seen as one matrix for each individual( with one column per path)

What you are describing will definitely require to call one of the predefined aggregation function . But how should create the row output from the population engine? Happy to have  a chat

**Comment by msevestre** [comment]
@Yuri05 Do you concur that the format that we return from the getOutputValue should be directy pluggable into the TLF lib?

**Comment by Yuri05** [comment]
> Do you concur that the format that we return from the getOutputValue should be directly pluggable into the TLF lib?

Agree. It would be nice to have outputs directly matching the TLF inputs specifications

**Comment by abdullahhamadeh** [comment]
This could be a possible series of steps for transforming the data from population enginer to the tlf aggregation stage
![image](https://user-images.githubusercontent.com/18409098/66418340-e02c1c00-e9cf-11e9-8129-270cb4a6a47e.png)

@pchelle does this look reasonable?
