### ISSUE TITLE
Output format for multiple outputs with different dimensions

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#203]
Follow up of https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/193

Assuming that I am simulating a population with threee putputs: 2 concentrations (Venous blood plasma and Arterial Blood Plasma) and a fraction (fraction metabolized xxx). 

How should the format of the data be returned so that it is conformed with TLF expectations?

* We need the data
* We also need the meta data (e.g. unit). 

I see two options, but please let me know if there are more way of doing this

1. Return one {data, metadata} combo per output.  (in our case 3)
2. Return one  {data, metadata} combo per dimension (in our case 2).

I feel that that option 1 is the more natural to understand but I may be wrong

Let me know your thoughts

FYI
@abdullahhamadeh @pchelle @PavelBal @Yuri05

**Comment by abdullahhamadeh** [comment]
The disadvantage of 2 is that you would need to make sure that whatever mathematical operation you are carrying out on an aggregation of a dataframe of type 2 makes sense.  Type 1 is more errorproof because it prevents you from taking, eg, the mean of a "wrong" combination of values in the dataframe.  If we have a mix of arterial and venous in the dataframe and aggregate by only by gender and then evaluate the mean for each group then the aggregation helper will return the means of all female entries and all male entries regardless of arterial/venous.  There may be cases where you might want to take an average of concentrations in a mix of compartments, but usually these functions are performed on values in only one compartment.

The advantage of 2 is you have fewer {data, metadata} sets.  For example, when defining "outputs" why stop at path (arterial/venous)?  Why not define: 
output 1:  male - venous blood plasma
output 2:  female - venous blood plasma
output 3:  male - arterial blood plasma
output 4:  female - arterial blood plasma
so that you then have 4 sets of {data,metadata}.  You can also stratify by IndividualID and have a different {data,metadata} for each individual.  So is there something special about path (apart from the aggregation argument above) that makes you define each path's values as a different output?

**Comment by Yuri05** [comment]
Regarding Abdullahs last question: do we get all this info (Gender, age, ...) per output as part of pop results as well?

**Comment by msevestre** [comment]
>: do we get all this info (Gender, age, ...) per output as part of pop results as well?

Not directly. This is part of the population. We probably should add all covariates as column in the output frame no?

>You can also stratify by IndividualID and have a different {data,metadata} for each individual. So is there something special about path (apart from the aggregation argument above) that makes you define each path's values as a different output?

I'd say practicability.  I am not sure it makes sense to deal with a 1000 data.frame if you could only have one . I have no good reason to say it, but it feels that having one data.frame per individual and output would go against the grain of the way of dealing with data in R

**Comment by Yuri05** [comment]
>Not directly. This is part of the population. We probably should add all covariates as column in the output frame no?

I would say: YES. Can imagine quite a few use cases where this information might be useful/required.

Apart from that: option 1 seems for me better as well (also in terms of "TLF philosophy")

**Comment by msevestre** [comment]
>Apart from that: option 1 seems for me better as well (also in terms of "TLF philosophy")

One per dimension or one per output? One per output could make sense also ?

**Comment by Yuri05** [comment]
One per output (what you defined as option 1 in the initial post :)

**Comment by msevestre** [comment]
oh yeah right :) lol

**Comment by msevestre** [comment]
then one per output it is. I am losing my mind sometime

**Comment by abdullahhamadeh** [comment]
How many paths (and hence dataframes) will there be if we go for option 1?

**Comment by msevestre** [comment]
well it depends on what the user selects. Typicallyu between 1 and 10?

**Comment by msevestre** [comment]
How should the output look like however? for each output, we would have two dataframe. Should it be a list of list?
something like 
list(
"Output1" = list(data, metaData),
"Output2" = list(data, metaData),
...
)

**Comment by msevestre** [comment]
@pchelle @abdullahhamadeh Is there a description of the meta data structure for a time profile plot?
I could not find it anywhere in the current TLF code

**Comment by msevestre** [comment]
All right I am propsing this for now
![image](https://user-images.githubusercontent.com/1041237/67120547-7ffb5e00-f1b7-11e9-93a8-c7ce8501a74e.png)

a list of list accessible by output path.

**Comment by pchelle** [comment]
If I understand correctly, the output is a list of paths for which we have a list of data and metaData. Works for me.

I don't think we have defined any time profile meta data so far.
By the way, for consistency of the units and dimensions of metaData, do you think these properties can use enum variables ?

**Comment by msevestre** [comment]
>If I understand correctly, the output is a list of paths for which we have a list of data and metaData. Works for me.

This is correct. Unfortunately, the code is still not ideal and it takes quite sometimes to create the dataset eventhough the data is already in memory, which is quite surprising. that's why I'd like some feedback from you and @abdullahhamadeh and @PavelBal on how to improve the code. 
We are talking about 1000 individual and 120 row per individual. That makes 10^6 rows. Is this a lot for a data.frame? Should we use something else like tibble?

**Comment by msevestre** [comment]
> By the way, for consistency of the units and dimensions of metaData, do you think these properties can use enum variables ?

I don't think so. We do not want to restric the user to only use our specific dimensions I would say. But even then, the enum for unit would be dependent on the dimension. That I don't think this can work nicely. For now, this is purely input. I don't think user will ever set it by hand anyways, or rarely

**Comment by msevestre** [comment]
done for now
