### ISSUE TITLE
setParameter/moleculeInitialValue: ignoreIfFormula

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#224]
Introduce additional argument `ignoreIfFormula`. If `TRUE`, the value will not be updated. `FALSE` by default?

**Comment by msevestre** [comment]
I don't understand

p is a formula

you call explicitely setParameter(p, 5) 
and you expect the value not to be updated?

**Comment by PavelBal** [comment]
If `p` is a parameter defined by a _constant_ formula, then the value is always updated.

If `p` is a parameter defined by any other type of formula, calling

`setParameter(p, 5)`
will update the value, while

`setParameter(p, 5, ignoreIfFormula = TRUE)`
will not.

The most prominent use case would be applying the set of parameters generated by `PKSimCreateIndividual` (or how we will call the respective function), where also some non-constant parameters are returned. In this case, I would like to iterate through all the parameters but only overwrite the constant ones.

**Comment by msevestre** [comment]
Just so that I understand the use case.

Why wouldn't you filter the list before?
constantParams = params[[isConstant=true]] oder wie auch immer es geht im R

**Comment by PavelBal** [comment]
Well I would have to iterate through all params and call `p$formula$isConstant` first. Of course doable, but would require more code and additional calls.

**Comment by msevestre** [comment]
@PavelBal Let's see the use cases for now. I don't want to have to add another parameter to filter out only talbe parameters, or only parameter that start with P etc..

What we could do is allow to pass a criteria function (takes an entity and returns a boolean) that will be applied to the list. This

so you define a isConstant <- function(p) p$formula$isConstant

then youi call setParameter(params, values, isConstant)

Obivously it gets trickier because do we filter the values array as well?

**Comment by msevestre** [comment]
(remember, values and params can be array).

**Comment by msevestre** [comment]
https://github.com/Open-Systems-Pharmacology/OSPSuite-R/pull/262/files

Let's close for now as the use case has probably become obsolete now that the lists returned by createIndividual do not have formula parameters anymiore
