### ISSUE TITLE
Basic UseCase: set and get Table Parameter

### ISSUE THREAD

**Issue by KatrinCoboeken** [Open-Systems-Pharmacology/OSPSuite-R#25]
set and get table parameter

**Comment by msevestre** [comment]
@KatrinCoboeken Can you describe the use case?
More specifically: Changing the value of table parameters is way easier than swapping a constant parameter for a table parameter.

**Comment by KatrinCoboeken** [comment]
If you have for example defined the solution profile of a tablet via a table, that was implemented in the old Toolbox as "table parameter", with a function set/getTableParameter to get and change the time and value column of the table. Something like that we will need also in the future.
I did not think of a switch between constant and table parameter.

**Comment by Yuri05** [comment]
> More specifically: Changing the value of table parameters is way easier than swapping a constant parameter for a table parameter.

In Mobi we could get this situation in the future if we e.g. switch from individual without aging to an individual with. 
Not sure however if this might be of interest in R as well

**Comment by PavelBal** [comment]
In general, the option to change parameter type between constant/formula/table would be great, but it would also work without, if it is too much work.

**Comment by msevestre** [comment]
> in general, the option to change parameter type between constant/formula/table would be great, but it would also work without, if it is too much work.

Not for this version for sure. Changing the type from constant to formula would require being able to create formula etc.. This becomes extremely complicated.

**Comment by Yuri05** [comment]
>Changing the type from constant to formula would require being able to create formula etc.. This becomes extremely complicated.

Agree, but with one exception: changing parameter from non-table (constant or formula) to table should be possible already in the first version.

**Comment by msevestre** [comment]
Why? Cannot we ask the user for the first version to do this type of changes in MoBi.
Changing parameter structure will require exposing building blocks to R, and allowing rebuild of simulation. This was never the plan and it will be very time consuming

**Comment by Yuri05** [comment]
There were some situations which required overwriting of constant parameters with a table (and overwriting of table parameters with a constant value).
That's why this 2 overwriting cases were implemented in SimModel and thus available in the Matlab/R-Toolbox.

I don't remember the concrete use cases at the moment and cannot say how urgent this is.
(probably solubility changes table vs. const)

Maybe @KatrinCoboeken can comment on this.

**Comment by msevestre** [comment]
Of course if we accept that the simulation is going to be manipulated directly, thus resulting in a mismatch between building block and simulation, we can do it directly at the simulation level. That would mean that reimporting in MoBi would produce a simulation that matches R. However recreating from Building block would NOT bring the TABLE Formula back.

I think this is a fair compromise considering that otherwise, it's a massive undertaking (and I don't know why we would want to spend time on that considering the few numbers of use cases)

**Comment by KatrinCoboeken** [comment]
I also can not remember the use cases where we needed to change constant  parameters to table parameters. So i would agree with Michael, let the user do this in Mobi. To change a table Parameter to a constant should be easy with a constant table.

**Comment by msevestre** [comment]
ok so implementing the fact that we can override a table parameter with a constant. This probably work as is but going to check it
