### ISSUE TITLE
createIndividualCharacteristics and createIndividual

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#314]
Why do we require the two steps for creating an individual parameter set?

```
humanIndividualCharacteristics <- createIndividualCharacteristics(species = Species$Human, population = HumanPopulation$European_ICRP_2002,
                                              gender = Gender$Male, weight = 70)
humanIndividual <- createIndividual(individualCharacteristics = humanIndividualCharacteristics)
```

Why not pass the individual values to `createIndividual` directly?

**Comment by msevestre** [comment]
A few reasons:
1/ we didn't want to have a method with dozens of parameters. Typically, you create an object that holds all the parameters. 
2/the first method is actually not required. One can create the object directly and set the properties. This is more of a convenience method so that people don't have to create the object. (I am not sure that this is a good idea as I'd rather people understanding that they can create object and set properties)
3/this object will allow very elegant code. Once you have an instance, you can simply change one property (for example age) and call the createIndividual method again. 
4/this object is required for .net. it is not possible to pass list of non primitive types to .net from R. Here we have a list of molecule ontogeny and managing an object with a list was required

**Comment by PavelBal** [comment]
Hm, I actually do not see any reason. What is the benefit of calling

```
humanIndividualCharacteristics <- createIndividualCharacteristics(species = Species$Human, population = HumanPopulation$European_ICRP_2002,
                                              gender = Gender$Male, weight = 70)
humanIndividual <- createIndividual(individualCharacteristics = humanIndividualCharacteristics)
```

over 

```
humanIndividual <- createIndividual(species = Species$Human, population = HumanPopulation$European_ICRP_2002,
                                              gender = Gender$Male, weight = 70)
```

**Comment by PavelBal** [comment]
Hm, I actually do not see any reason. What is the benefit of calling

```
humanIndividualCharacteristics <- createIndividualCharacteristics(species = Species$Human, population = HumanPopulation$European_ICRP_2002,
                                              gender = Gender$Male, weight = 70)
humanIndividual <- createIndividual(individualCharacteristics = humanIndividualCharacteristics)
```

over 

```
humanIndividual <- createIndividual(species = Species$Human, population = HumanPopulation$European_ICRP_2002,
                                              gender = Gender$Male, weight = 70)
```

**Comment by PavelBal** [comment]
OK, that's a valid use case ;)

**Comment by msevestre** [comment]
But if the consensus is to go back to a method with a long list of parameters, I am good with this.
/cc @Yuri05

**Comment by PavelBal** [comment]
No it's ok, you just showed a valid use case, I did not think of that one.
