### ISSUE TITLE
Build time increased from 12 to 20 min with vignettes

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#392]
@PavelBal Can we make sure that the example used in the vignettes do not require so much time to build? 
Or what can be the cause of such as jump in build time?

**Comment by PavelBal** [comment]
Probably due to sensitivity analysis, but 8 min are really much... But I cannot imagine anything besides SA.

At each build, all examples in the vignettes are calculated. So we either reduce the examples (e.g., do not show how to calculate SA for all constant (default) parameters), or have to live with it.

**Comment by PavelBal** [comment]
I will take a look if we can re-use some results in the vignettes..

**Comment by msevestre** [comment]
WE can use a simple model that has 4 parameters (such as the simple.pkml). This should be ready in a matter of seconds

**Comment by PavelBal** [comment]
Makes sense, will update.

**Comment by msevestre** [comment]
Yep fixed with #402
