### ISSUE TITLE
Feature: Create and modify DataRepository and DataColumn

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#508]
Right now it is possible to load data repositories from PKML, but a new repository (or data column) cannot be created in R.

I think it should also be possible to create such repositories in R, e.g. from loaded excel data, or from simulation results. This would provide a unified infrastructure for handling data, allow exporting of data to PKML, and I guess simplify communication with parameter identification configuration in future.

Required interfaces:

### BaseGrid
 - Constructor
   - `public BaseGrid(string name, IDimension dimension)`
     - What is usually used for `name`?
 - Are values always in `baseUnit`?
 - Set values
   - `setValues()`

### DataColumn
- Constructor
  - `public DataColumn(string name, IDimension dimension, BaseGrid baseGrid)`
   - What is usually used for `name`?
 - Are values always in `baseUnit`?
 - `setDataRepository()`
   - Why is this required?
 - Set values
   - `setValues()`

### DataRepository
- Constructor
  - `public DataRepository()`
- setBaseGrid
- addColumn
  - Are there use cases for multiple columns per repository? When should it be used?
 - removeColumn
 - setMetaData
   - Could not find a setter or adder for extended properties

@msevestre What do you think of this?

**Comment by msevestre** [comment]
>I think it should also be possible to create such repositories in R, e.g. from loaded excel data,

This requires the importer :) Unless we do it via the configuration files without any UI. Could be an option that we discussed already

>I guess simplify communication with parameter identification configuration in future.

Could be. In fact, the output of a simulation IS a DataRepository that we transform into something smaller so that it fits the format of a population Simulation

Everything else is doable and exists already, at least at the .net level and could be exported. There is a concept of related columns (e..g ERRORS for another column) that would need to be exposed as well

**Comment by PavelBal** [comment]
> This requires the importer :) Unless we do it via the configuration files without any UI. Could be an option that we discussed already

In the first step it would be already a gain to be able to create `DataRepository` with numerical data from R. Later, we could add support of importer via CLI.
