### ISSUE TITLE
set up continuous integration and delivery with github actions

### ISSUE THREAD

**Issue by maxheld83** [Open-Systems-Pharmacology/OSPSuite-R#520]

**Comment by PavelBal** [comment]
Wrong repo.

**Comment by msevestre** [comment]
Does it make sense to use GitHub actions for our R projects?

**Comment by PavelBal** [comment]
## Setting up CI for R repositories

Let us discuss what is the most appropriate way to set up continuous integration for our R repositories - in particular, the question "AppVeyor" vs "GitHub actions". I do not have a deep understanding of CI so I just start a discussion and maybe @msevestre and @maxheld83 can discuss and exchange your experience.

### Tasks
- On every push:
  - Run `R CMD check`
  - Run `R CMD build`
  - Run `R CMD INSTALL`
  - Check code coverage
With the current solution with AppVeyor for ospsuite, TLF-Library, and OSPSuite.ReportingEngine, the whole R environment is set up every time the script is triggered. Does it have to be that way? Or can an environment be prepared, e.g. by installing R once, and then just updating the dependencies? I.e., these tasks must be executed either once or on every push:
- Install/update dependency packages from CRAN
- Install/update dependency packages from repositories: 
  - [rClr](https://github.com/Open-Systems-Pharmacology/rClr)
  - [ospsuite](https://github.com/Open-Systems-Pharmacology/OSPSuite-R)
  - [reporting engine](https://github.com/Open-Systems-Pharmacology/OSPSuite.ReportingEngine)
  - [TLF](https://github.com/Open-Systems-Pharmacology/TLF-Library)
The list of dependencies is different for every project. Also, it is probably not sufficient to install a released version of "our" packages, but have to access the latest develop-build.

All these steps must be performed in a Windows-environment with an installed version of (nightly build) PK-Sim.

Additionally, a Linux-build of the ospsuite-r may be of interest, but probably not a high prio rn.

Please add the missing requirements and your thoughts on how to implement this in AppVeyor and GitHub actions.

**Comment by msevestre** [comment]
>the whole R environment is set up every time the script is triggered. Does it have to be that way? 

No it does not. But the time for this step is about 3 min and compared to some of the build steps we have, specifically building vignettes etc...it was not worth the time investments. But this is something that could be looked at (we can use some cache on appveyor for instance or even bring our own VM!). The problem with the cache is that it will cache also packages installed during build time so we would have to be careful to override them etc...

All doable but probably not that easy to get right

**Comment by maxheld83** [comment]
> Wrong repo.

My bad, sorry about the noise.

**Comment by maxheld83** [comment]
I'm coming at this from the outside, so apologies in advance if I'm missing something.

It seems to me that OSPSuite-R might benefit from creating a canonical and transportable compute environment, in which they are known to pass (as per CI).
**Docker**, I guess is the standard way to do this.

I think there may be some **advantages to containerisation**:

1. This way, the compute env would only have to be defined *once*, and in a CI-agnostic way -- if the service (say, AppVeyor, or GitHub Actions) supports docker, we're good.
2. The same images could be used quick testing on local clients, 
3. ... and potentially even interactive development.
4. we can rely on existing docker tooling for other concerns (build caching, etc.)
5. downstream users can take layers or the entire image from here for their own CI

The `Dockerfiles` for linux already exist, but perhaps they can be added to the (GHA) CI suite #523.

The problem that @PavelBal quickly pointed me to, that I missed is that OSPSuite-R doesn't (fully) support Linux, which is what most docker images are based on, and that fixing that might be quite the undertaking (though possible).
So I'm trying to use windows docker containers for that (see #524).

I'll report back here depending on how these two go.

**Comment by Yuri05** [comment]
Following the idea in https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/523#issuecomment-844023594 I have created "base" images for R 3.6 and R 4.1 and CentOS 7 and Ubuntu 18.04 (_bionic_). You can find them under the [OSP Packages](https://github.com/orgs/Open-Systems-Pharmacology/packages) (images called "`base-XXX`", e.g. `base-r3.6.3-centos7`). Images are setup in https://github.com/Open-Systems-Pharmacology/Docker-Base-Images/.
At the moment base images contain everything which is required for the **installation and execution** of the OSP R packages; for the **compilation** of R packages some tools might be missing - which can be easily fixed in the future.

Using those base images I have also pushed 2 images containing the latest (pre-)released versions of the OSP R packages (_tlf_, _ospsuite-r_, _ospsuite.reportingengine_):
<img width="500" src="https://user-images.githubusercontent.com/25061876/120921329-7a6fc600-c6c3-11eb-94d5-acaacf34909f.png">
Those images are created "**manually**" in https://github.com/Open-Systems-Pharmacology/Docker-Images. If the image creation is setup as part of the CI, this "manual" creation would become obsolete.

**Comment by IndrajeetPatil** [comment]
Closing in favor of https://github.com/Open-Systems-Pharmacology/Suite/issues/94
