### ISSUE TITLE
ospUnits$`Concentration (mass)` shows no suggestions

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#563]
No idea why, but I don't see any suggestions for 

`ospUnits$`Concentration (mass)`$` (also for molar). I think the problem is the `(`

**Comment by msevestre** [comment]
@abdullahhamadeh can you check this out?

**Comment by abdullahhamadeh** [comment]
@PavelBal is right, if you remove the brackets you can see the suggestions.  I am reluctant to change the name of this item in the list because the string (including the brackets) is part of ospsuite and can be passed to `ospUnits` as an argument from a script that takes the string directly from the package somehow.  Moreover you might need to pass the dimension with the brackets to functions like `toBaseUnit()`.  So unless we change this string globally I am not sure we should change it here.

**Comment by msevestre** [comment]
We cannot chnage the string globally. But can we change the property name so that it works as expected in R? Otherwise it's clearly a bug
And why it the `(` creating an issue?

**Comment by msevestre** [comment]
would it work if we repleace () with [] (just the property name not in the actual string )

**Comment by abdullahhamadeh** [comment]
square brackets would work
![image](https://user-images.githubusercontent.com/18409098/127023880-c62405c9-2722-4f41-88ed-f5adeaf19e39.png)

but does that help?  If the property name ( "Concentration (mass)" ) changes, then you can no longer pass the string "Concentration (mass)" from other parts of the suite

**Comment by PavelBal** [comment]
Yes the problem with changing the brackets is that such subsetting:

`ospUnits[["Concentration (molar)"]]` (or `ospUnits[[ospDimensions$`Concentration (molar)`]]`) will fail.

**Comment by msevestre** [comment]
The Property name will not change. This is a constant that will remain as is

So if [ is a problem? What about\ or _ or sthg like this . This is purely to make sure we can use the functionality

**Comment by msevestre** [comment]
So do we care? :)

**Comment by abdullahhamadeh** [comment]
We do! PR #608
