### ISSUE TITLE
DisplaUnit for UserDefinedPKParameters

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#663]
I cannot understand how to use the `displayUnit` of a user defined PK parameter. After adding the parameter and calculating PK parameters with `calculatePKAnalyses`, I only have access to the class `QuantityPKParameter` where the values are always in base unit... How can I output the values in a specific unit?

**Comment by msevestre** [comment]
The display unit is the value that will be used when you export your values
```
userDefinedPKParameter <- addUserDefinedPKParameter(name = "Test", standardPKParameter = StandardPKParameter$AUC_tEnd, displayName = "toto", displayUnit = "mg")
```

and later

```
populationPkAnalyses <- calculatePKAnalyses(populationResults)
df <- pkAnalysesAsDataFrame(populationPkAnalyses)
````

![image](https://user-images.githubusercontent.com/1041237/141332376-3ea767df-a466-4afd-8f1d-1cbc5606fb29.png)

**Comment by PavelBal** [comment]
ok, so it only works with `asDataFrame`.

**Comment by PavelBal** [comment]
Thanks

**Comment by msevestre** [comment]
>ok, so it only works with asDataFrame.

I am not sure. In order to calculate the value in "displayUnit", you need access to the whole simulation which we do not have in the typical PKParameter. Maybe we could think about it .... e.g. save the display unit as well in the QuantityPKParameter so that it would be available in the R object as well
