### ISSUE TITLE
stop converting characters to factors in  `pkAnalysesAsDataFrame()`?

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite-R#673]
Parameters, units, etc. are not categorical data, and treating them as such makes it difficult to work with them further.

If you agree, the calls to `readr::col_factor()` here can be replaced with `readr::col_character()`:

https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/624745eee2180139dbcbef45a0ee5153b6b67291/R/utilities-pk-analysis.R#L74-L80

The only downside to this is that character/string columns will take up more space than factors, which are integers in disguise, so the returned dataframes will be slightly heavier.

**Comment by msevestre** [comment]
Is this a breaking change?

**Comment by msevestre** [comment]
I agree with this change. The only reason we have it as factor is because....euh....wait... no idea

**Comment by PavelBal** [comment]
All pk analyses workflow is not straightforward to me, so go ahead.

**Comment by msevestre** [comment]
>All pk analyses workflow is not straightforward to me

What does this mean? If something is not clear, it should be mentioned and discussed don't you think?

As far as breaking change is concerned, my question is simple, independently from how this is being used:
If someone was relying on the dataframe from v10 with factors to do some stuff, and in v11 it is not factor anymore, will it break the code or not? If yes, we need to mark this as a breaking change in our release note

@IndrajeetPatil Can you create a label: Breaking change so that we can tag those changes that we are adding in v11 (for instance I would not export all the validatexxx again)

**Comment by IndrajeetPatil** [comment]
> If someone was relying on the dataframe from v10 with factors to do some stuff, and in v11 it is not factor anymore, will it break the code or not?

This is hard to predict because of the coercion rules, but since, in most contexts, R will convert factor to character and vice versa, I don't think it will be a breaking change. But I will make a note of it as such, just to be safe.

``` r
x <- factor(c("z", "y", "x"), levels = c("x", "y", "z"))
as.character(x)
#> [1] "z" "y" "x"

y <- c("z", "y", "x")
as.factor(y)
#> [1] z y x
#> Levels: x y z
```

<sup>Created on 2021-12-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

> Can you create a label: Breaking change

Done.
