### ISSUE TITLE
Create DataSet from SimulationResults

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#687]
So we can have all possible data in the same structure.

**Comment by msevestre** [comment]
WHY?

DataSet also has one x and one y. SimulationResults as one x and n y

**Comment by IndrajeetPatil** [comment]
My 2 cents:

I think having the same column naming schema would make it pretty easy to combine them (either in user workflows or for us while implementing the `toDataFrame()` method for `DataCombined` object)

- observed data -> DataSet -> toDataFrame -> df_obs
- simulated data -> DataSet -> toDataFrame -> df_sim

And then they can simply be bound together without trouble, e.g. `dplyr::bind_rows(df_obs, df_sim)`

That said, we will need to also have a column identifying the nature of the data, otherwise which `x` and `y` are from observed and which from simulated will be hard to tell (I am pretty sure there is already this information contained somewhere in these dataframes; I just don't know these outputs that well).

**Comment by msevestre** [comment]
As long as you have  

observed data -> DataSet -> toDataFrame -> df_obs
simulated data -> SimulationResults -> toDataFrame -> df_sim

you are good to go right?

**Comment by IndrajeetPatil** [comment]
Yes, but AFAIK, we don't have SimulationResults -> toDataFrame part implemented yet, right?

**Comment by msevestre** [comment]
Maybe not. But this is trivial since we can export to csv

**Comment by msevestre** [comment]
>will need to also have a column identifying the nature of the data, otherwise which x and y are from observed and which from simulated will be hard to tell 
in't it DataCombined?

**Comment by IndrajeetPatil** [comment]
> in't it DataCombined?

Yes, of course. This will be trivial to implement in `DataCombined`, but I meant the _individual_ dataframes themselves should also contain this (observed versus simulated) information.

So, if someone created **only** dataframe `df`  for `DataSet` via `observed data -> DataSet -> toDataFrame` route, then the `df` should hold clues whether this is observed and simulated data, and they shouldn't have to look at the script. If I write to a csv or something, they will also lose this information.

**Comment by msevestre** [comment]
I hope that we will always use the higher level construct and derive the df from this if required

**Comment by IndrajeetPatil** [comment]
I think this can be closed?
