### ISSUE TITLE
Almost all R6 class should be exported

### ISSUE THREAD

**Issue by IndrajeetPatil** [Open-Systems-Pharmacology/OSPSuite-R#702]
I see. Still. you can use the object from a returned value (sim <- loadSimulation(...)) and use sim in your code (no :: or :::) here. I agree with you. Almost all R6 class should be exporter, specifically if they are part of exported API methods.

_Originally posted by @msevestre in https://github.com/Open-Systems-Pharmacology/OSPSuite-R/pull/695#discussion_r768756479_

**Comment by PavelBal** [comment]
I don't know. What exactly is the difference between exporting and not exporting the class? The way I see it, the only difference is that the user cannot create a new object using the constructor if the class is not exported. And for most of the classes that we have, creating a new object of the class by user is not the intended workflow. For example, we are not exporting `Simulation` because the user should not create a simulation from scratch. `DataSet` is an exported class, as the user can create a new data set and populate it from scratch.

So far, the API seems to work as expected, and I am not sure why we should change something here.

**Comment by IndrajeetPatil** [comment]
The issue is not about whether something is working or not, the issue is about having documentation that faithfully reflects our API.

If you look at our Reference section on the website (https://www.open-systems-pharmacology.org/OSPSuite-R/reference/index.html), you see all the functions, exported or not, and this is because we are not including the needed tags in the roxygen documentation. As a user, I am at loss as to what is important and what isn't, which defeats the purpose of the documentation.

So we have two options:

1. All objects we don't want users to get in the habit of using should get the tag `#' keyword include` (which is what I had done in the closed PR).

2. All objects we expect will be useful for the users should get the `#' export` tag. 

Yes, things are working as they are now, but we are just accumulating technical debt.

**Comment by msevestre** [comment]
Assuming internal and not include is meant. 

I think we should do both so that it's clear since the implicit behavior is **not** clear. I would not expect internal stuff to be exported by default, also methods without roxygen docs such as our .getXx methods that are private

This should be part of our PR checklist.

**Comment by IndrajeetPatil** [comment]
Closing in favor of API discussion in https://github.com/Open-Systems-Pharmacology/OSPSuite-R/issues/798.
