### ISSUE TITLE
3 warnings in test. Can we fix them? 

### ISSUE THREAD

**Issue by msevestre** [Open-Systems-Pharmacology/OSPSuite-R#764]
== Testing test-utilities-entity.R =============================================
[ FAIL 0 | WARN 3 | SKIP 0 | PASS 8 ]

-- Warning (test-utilities-entity.R:17:3): It throws an error when no valid 'compareBy' is provided --
NAs introduced by coercion
Backtrace:

**Comment by IndrajeetPatil** [comment]
They are coming from this test:

https://github.com/Open-Systems-Pharmacology/OSPSuite-R/blob/e24378edc4e03d1360b18f06898ae91dec461fa1/tests/testthat/test-utilities-entity.R#L17

Because of the following comparison:

``` r
ospsuite.utils::enumGetKey(ospsuite::CompareBy, 2)
#> Warning in which(enum == value): NAs introduced by coercion

#> Warning in which(enum == value): NAs introduced by coercion

#> Warning in which(enum == value): NAs introduced by coercion
#> NULL
```

<sup>Created on 2022-04-05 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>
