### ISSUE TITLE
`runSimulations` should always return a named list, even if only one simulation is executed

### ISSUE THREAD

**Issue by PavelBal** [Open-Systems-Pharmacology/OSPSuite-R#895]
Currently, `runSimulation` returns a named list of `SimulationResults` (with IDs of simulations as keys) when mutliple simulations are passed, or only one `SimulationResults` object. I do not think that the type of the output should be different as it leads to some ugly checks in the code when using this function (I have to check if the output is a list or a single object to decide how to access the results).

I propose to always return a named list. `runSimulation` (without an `s`) should continue to return only one result (aditionally, we should introduce a validation that only one simulation is passed).

@msevestre if you agree I will make a PR.

**Comment by IndrajeetPatil** [comment]
I am not sure about the latter part. 

In R, since there are no scalars, it's a bit unusual to have one function for scalar and another for vector arguments.

Even in _ospsuite_, we follow this pattern. For example,

- `addOutputs(quantitiesOrPaths)` works with a scalar argument for `quantitiesOrPaths` parameter
- `addOutputs(quantitiesOrPaths)` **also** works with a vector argument for `quantitiesOrPaths` parameter

We don't have an additional `addOutput(quantityOrPath)` (note singulars) function.

But, we are deviating from this pattern with two separate functions here:

- `runSimulation(simulation)` **only** works with a scalar argument
- `runSimulations(simulations)`  **only** works with a vector argument

Why not follow the same design pattern as `addOutputs(quantitiesOrPaths)` and have _only_ the `runSimulations(simulations)` function that:

- handles both scalar and vector arguments
- consistently returns a named list

Am I missing something here?

**Comment by PavelBal** [comment]
`runSimulation(simulation)` has been there forever, and removing it would break all the code users already have.

**Comment by msevestre** [comment]
I don't mind leaving this method as it is more of a convenience method for most use cases. I have used the ospsuite-r for a few projects and I never have the need to simulate multiple simulations at once 
It's much easier for me to say res <- runSimulation(simulation) than res <- runSimulations(simulation)[1] .
So a shortcut method for better UX experience. I like it

**Comment by msevestre** [comment]
@IndrajeetPatil Note that this is not about the parameter [in] but the parameter [out]
